import Foundation

enum Brand {
    static let name = "Processly"
    static let proName = "Processly Pro"
    static let watermarkFree = "Generated by Processly (Free)"
    static let tagline = "Turn messy notes into clear processes instantly"
    static let domain = "processly"
}
